#:kivy 2.3.0

#<CustomDropDown>:
#    size_hint_y: None
#    size_hint_x: None
#    width: 100
#    height: 60
#    on_hover_leave: self.dismiss
#
#    PointedButton:
#        text: 'My first Item'
#        size_hint_y: None
#        height: 44
#        on_release: root.select(self.text)
#    PointedButton:
#        text: 'My first and half Item'
#        size_hint_y: None
#        height: 44
#        on_release: root.select(self.text)
#    PointedButton:
#        text: 'My second Item'
#        size_hint_y: None
#        height: 44
#        on_release: root.select(self.text)

# ------------- CONTENT -------------
<Home>:
    # [padding_left, padding_top, padding_right, padding_bottom], [padding_horizontal, padding_vertical] or [padding]
    padding: [15]

    AnchorLayout:
        anchor_x: 'center'
        anchor_y: 'center'

        BoxLayout:
            orientation: 'vertical'
            size_hint_min_x: 530
            size_hint_min_y: 430
            size_hint_max_x: 900
            size_hint_max_y: 1300
            spacing: 15

            BoxLayout:
                orientation: 'vertical'
                size_hint_y: .3
                spacing: 15
                padding: [15,15]
                size_hint_min_y: 210
                size_hint_max_y: 300

                canvas.before:
                    Color:
                        rgba: .15, .15, .15, .3
                    Rectangle:
                        pos: self.pos
                        size: self.size

                BoxLayout:
                    size_hint_y: None
                    size: [self.size[0], 50]
                    spacing: 10
                    id: worldChoiceContainer

                    PointedSpinner:
                        id: world_chooser_spinner
                        text: 'Choose World...'
                        on_press: world_chooser_spinner_arrow_gif.anim_delay = 1/24
                        on_press: world_chooser_spinner_arrow_gif._coreimage.anim_reset(True)
                        Image:
                            id: world_chooser_spinner_arrow_gif
                            source: 'res/images/icons8-pfeil_-ausklappen-72-alphaWhite.gif'
                            center: [self.parent.right - 30, self.parent.center[1]+2]
                            size_hint_x: None
                            size_hint_y: None
                            size: [30, 30]
                            allow_stretch: False
                            opacity: 1
                            anim_loop: 1
                            anim_delay: -1

#                    PointedButton:
#                        id: dropdown_main_button
#                        text: 'Choose World...  '
                        #Image:
                        #    id: dropdownarrow_gif
                        #    source: 'res/images/icons8-pfeil_-ausklappen-72.gif'
                        #    center: [self.parent.center[0] + 50, self.parent.center[1]]
                        #    height: 30
                        #    allow_stretch: False
                        #    opacity: 1
                        #    anim_loop: 1
                        #    anim_delay: -1

                    ReactiveButtonWithToolTip:
                        id: editWorldsListButton
                        tooltip_text: "Edit Worlds..."
                        size_hint_y: 1
                        size_hint_x: None
                        size: [self.size[1]+5,self.size[1]]
                        Image:
                            id: edit_gif
                            source: 'res/images/icons8-bearbeiten-ezgif.com-instagif-less-white.gif'
                            center: self.parent.center
                            height: 30
                            allow_stretch: False
                            opacity: 1
                            anim_loop: 1
                            anim_delay: -1

                AnchorLayout:
                    anchor_y: 'center'
                    anchor_x: 'center'
                    size_hint_y: None
                    size_hint_x: 1
                    height: 4

                    canvas:
                        Color:
                            rgba: rgba(63, 63, 63)
                        Rectangle:
                            pos: self.x, self.center_y - 1
                            size: self.width, 2

                BoxLayout:
                    orientation: 'vertical'
                    spacing: 10

                    Label:
                        size_hint_y: .3
                        size_hint_x: None
                        size: [self.texture_size[0], self.size[1]]
                        text: 'Git Commit Message:'
                    BoxLayout:
                        spacing: 10
                        TextInput:
                            text: 'Edit here!'
                        Button:
                            size_hint_x: None
                            size: [self.size[1]+10,self.size[1]]
                            text: 'Save'


            BoxLayout:
                size_hint_y: .5
                size_hint_x: 1
                padding: 10, 3, 0, 3
                spacing: 0

                canvas.before:
                    Color:
                        rgba: .15, .15, .15, .3
                    Rectangle:
                        pos: self.pos
                        size: self.size

                CustomScrollView:
                    id: console_log_scrollview
                    Label:
                        id: console_log

                        size_hint_y: None
                        height: self.texture_size[1]
                        text_size: self.width, None
                        padding: [0,0]
                        font_name: "res/fonts/JetBrainsMono-VariableFont_wght.ttf"
                        color: 1, 1, 1, .4
                        text: ""

            BoxLayout:
                size_hint_y: .15
                size_hint_x: 1
                size_hint_min_y: 100
                size_hint_max_y: 150
                padding: [0,0]
                spacing: 15

                PointedSpinner:
                    size_hint_x: None
                    size: [self.size[1]+10,self.size[1]]
                    id: game-build
                    text: 'Stable'
                    values: ('Stable', 'Experimental')

                    on_press: game_mode_chooser_spinner_arrow_gif.anim_delay = 1/24
                    on_press: game_mode_chooser_spinner_arrow_gif._coreimage.anim_reset(True)
                    Image:
                        canvas.before:
                            PushMatrix
                            Rotate:
                                angle: 180
                                axis: 0, 0, 1
                                origin: self.center
                        canvas.after:
                            PopMatrix
                        id: game_mode_chooser_spinner_arrow_gif
                        source: 'res/images/icons8-pfeil_-ausklappen-72-alphaWhite.gif'
                        center: [self.parent.center[0], self.parent.center[1]+25]
                        size_hint_x: None
                        size_hint_y: None
                        size: [30, 30]
                        allow_stretch: False
                        opacity: 1
                        anim_loop: 1
                        anim_delay: -1

                PointedButton:
                    id: launch_button

                    background_normal: ''
                    background_down: ''
                    background_disabled_down: ''
                    background_disabled_normal: ''
                    background_color: rgba(229, 148, 69) # from ingame screenshot
                    outline_color: .2, .2, .2, 0
                    outline_width: 4
                    font_size: 48
                    line_height: 1.2
                    font_name: 'res/fonts/Satisfontory_v1.5.ttf'
                    size: self.size
                    text: 'Launch'

                    on_press: launch_button.background_color = rgba(193, 94, 0) # Press state color
                    on_release: launch_button.background_color = rgba(229, 148, 69) # Normal state color, but is a single click launch


                    # vielleicht erst durch code machen, dann kann ich das je nach aktuellem zustand ändern lassen
                    on_press: launch_button.text = ''
                    on_press: launch_button.disabled = True

                    # das hier für: - ist schon irgendwo sichtbar und angehalten und wird bei laden gestartet.
                    on_press: working_gif.anim_delay = 1/60
                    on_press: working_gif._coreimage.anim_reset(True)
                    on_press: working_gif.opacity = 1

                    # ideen:
                    #  - ist schon irgendwo sichtbar und angehalten und wird bei laden gestartet.
                    #  - ist irgendwo ist ein anderes symbol sichtbar und wird bei laden mit gif ersetzt.
                    #  - ist nirgends sichtbar und wird bei laden sichtbar.
                    Image:
                        id: working_gif
                        source: 'res/images/Infinity@1x-25.0s-200px-200px_grey.gif'
                        center: self.parent.center
                        size: 150, 150
                        allow_stretch: False
                        opacity: 0
                        anim_delay: -1
