#:kivy 2.3.0

<ListLabel>:
    text_size: self.width, None
    size_hint: 1, None
    size: self.size[0], self.texture_size[1]
#    padding: 0, 10, 10, 10
    padding: 0, 10, 4, 10

<EditWorldsDialog>:
    orientation: 'vertical'
    padding: 0, 10, 0, 0
    spacing: 10

    StackLayout:
        orientation: 'rl-tb'
        size_hint_y: None
        height: 40
        spacing: 10

        ReactiveButtonWithToolTip:
            id: addWorldButton
            tooltip_text: "Add World..."
            text: "+"
            font_size: 28
            size_hint_y: 1
            size_hint_x: None
            size: [self.size[1]+5,self.size[1]]
#            Image:
#                source: 'res/images/add.png'
#                center: self.parent.center
#                height: 30
#                allow_stretch: False
#                opacity: 1

        # bc of 'right-to-left' orientation of StackLayout, the first Widget is the most right one.
#        PointedButton:
#            text: 'Add world...'
#            size_hint_y: 1
#            size_hint_x: None

        #Label:
        #    text: 'kek'
        #    width: 30
        #    size_hint_y: 1
        #    size_hint_x: None
        #    canvas.before:
        #        Color:
        #            rgba: 1, 0, 0, .8
        #        Rectangle:
        #            size: self.size
        #            pos: self.pos

    CustomRecycleView:
        id: worldEditList
        viewclass: 'ListLabel'

        RecycleBoxLayout:
            default_size: None, dp(56)
            default_size_hint: 1, None
            size_hint_y: None
            height: self.minimum_height
            orientation: 'vertical'

    BoxLayout:
        size_hint_y: None
        height: 50
        spacing: 5
        PointedButton:
            text: "Confirm"
            on_release: root.confirm()
        PointedButton:
            text: "Cancel"
            on_release: root.cancel()
